{
 "title": "Sentiment Dasbhoard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Filter",
    "label": "Hashtag",
    "query": "select distinct filter from analysis"
   }
  ]
 },
 "panels": [
  {
   "title": "List",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  text as label\nFROM \n  analysis\nWHERE\n  $__unixEpochFilter(timestamp/1000)\nORDER BY timestamp desc"
    }
   ]
  },
  {
   "title": "All The Time",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sentiment AS metric,\n  count(sentiment) as value\nFROM analysis\nGROUP BY sentiment, 2"
    }
   ]
  },
  {
   "title": "Sentiment Chart Time Filtered",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sentiment AS metric,\n  count(sentiment) as value\nFROM analysis\nwhere\n  $__unixEpochFilter(timestamp/1000)\nGROUP BY sentiment, 2"
    }
   ]
  },
  {
   "title": "Client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(source) as source,\n  count(*) as total\nFROM \n  analysis\ngroup by source\norder by total desc"
    }
   ]
  }
 ]
}