version: "3"

services: 
  mysql:
    container_name: twitter_mysql
    image: mysql:5.7.33
    command: --default-authentication-plugin=mysql_native_password  --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MSYQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes: 
    #   - ./data:/var/lib/mysql
    ports: 
      - 3306:3306