version: "3"
services: 
  grafana:
    container_name: twitter_grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes: 
      - ./plugins:/var/lib/grafana/plugins
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports: 
      - 3000:3000